global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot App Metrics
  - job_name: vm_1_app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.123.10:8080']

  - job_name: vm_2_app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.123.11:8080']

  - job_name: vm_3_app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.123.12:8080']

  # Node Exporter Metrics
  - job_name: vm_1_node
    static_configs:
      - targets: ['192.168.123.10:9100']

  - job_name: vm_2_node
    static_configs:
      - targets: ['192.168.123.11:9100']

  - job_name: vm_3_node
    static_configs:
      - targets: ['192.168.123.12:9100']
