global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: vm_1
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.123.10:8080']

  - job_name: vm_2
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.123.11:8080']

  - job_name: vm_3
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['192.168.123.12:8080']
