name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Hub credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Project with Maven
        run: mvn clean package

      - name: Extract Git commit short hash
        run: echo "VERSION=$(git log -1 --pretty=format:%h)-SNAPSHOT" >> $GITHUB_ENV

      - name: Create .env file for docker-compose
        run: echo "VERSION=${{ env.VERSION }}" > .env

      - name: Build Docker image using docker-compose
        run: docker compose build --build-arg JAR_FILE=vm-inspector.jar

      - name: Push Docker image to Docker Hub
        run: docker push 1602047/vm-inspector:${{ env.VERSION }}
