name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.set-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Hub credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Project with Maven
        run: mvn clean package

      - name: Extract Git commit short hash and set output
        run: |
          VERSION=$(git log -1 --pretty=format:%h)-SNAPSHOT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Create .env file for docker-compose
        run: echo "VERSION=${{ env.VERSION }}" > .env

      - name: Build Docker image using docker-compose
        run: docker compose build --build-arg JAR_FILE=vm-inspector.jar

      - name: Push Docker image to Docker Hub
        run: docker push 1602047/vm-inspector:${{ env.VERSION }}

  deploy-vm1:
    needs: build
    runs-on: [self-hosted,vm1]
    steps:
      - name: Pull and run latest image on VM1
        run: |
          VERSION=${{ needs.build.outputs.image_version }}
          docker pull 1602047/vm-inspector:$VERSION
          docker run -d -p 8080:8080 -p 8099:8010 -v /etc/hostname:/vm_hostname 1602047/vm-inspector:$VERSION

  deploy-vm2:
    needs: build
    runs-on: [self-hosted,vm2]
    steps:
      - name: Pull and run latest image on VM2
        run: |
          VERSION=${{ needs.build.outputs.image_version }}
          docker pull 1602047/vm-inspector:$VERSION
          docker run -d -p 8080:8080 -p 8099:8010 -v /etc/hostname:/vm_hostname 1602047/vm-inspector:$VERSION

  deploy-vm3:
    needs: build
    runs-on: [self-hosted,vm3]
    steps:
      - name: Pull and run latest image on VM3
        run: |
          VERSION=${{ needs.build.outputs.image_version }}
          docker pull 1602047/vm-inspector:$VERSION
          docker run -d -p 8080:8080 -p 8099:8010 -v /etc/hostname:/vm_hostname 1602047/vm-inspector:$VERSION
